version: '3.8'
services:
  db:
    container_name: auth_demo_postgres
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: auth_demo
      POSTGRES_USER: auth_demo
      POSTGRES_PASSWORD: auth_demo
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  adminer:
    container_name: auth_demo_adminer
    image: adminer
    restart: always
    ports:
      - "8085:8080"
