spring:
  application:
    name: auth-demo

  jpa:
    open-in-view: false
    database: postgresql

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5433/auth_demo}
    username: ${JDBC_DATABASE_USERNAME:auth_demo}
    password: ${JDBC_DATABASE_PASSWORD:auth_demo}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

jwt:
  token-secret: ${JWT_TOKEN_SECRET:as$l1da)knq32woy238}
  user-token-expired-in-days: ${USER_JWT_TOKEN_EXPIRED_IN_DAYS:30}
